# Generated by Django 5.1.4 on 2024-12-21 00:44

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatedProductSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_comment='Affiliated site name', max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Creation datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Updated datetime')),
                ('user', models.ForeignKey(db_comment='User who created the record', on_delete=django.db.models.deletion.CASCADE, related_name='user_aps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'affiliated_product_sites',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Product title', max_length=250, unique=True)),
                ('slug', models.SlugField(db_comment='Slug', unique=True)),
                ('short_description', tinymce.models.HTMLField(db_comment='Product short description')),
                ('description', tinymce.models.HTMLField(db_comment='Product description')),
                ('tags', models.CharField(blank=True, db_comment='Tags', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Creation datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Updated datetime')),
                ('owner', models.ForeignKey(db_comment='Product record owner', on_delete=django.db.models.deletion.CASCADE, related_name='product_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='AffiliatedProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Creation datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Updated datetime')),
                ('user', models.ForeignKey(db_comment='User who created the record', on_delete=django.db.models.deletion.CASCADE, related_name='user_apl', to=settings.AUTH_USER_MODEL)),
                ('affiliated_product_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.affiliatedproductsite')),
                ('product', models.ForeignKey(db_comment='Product', on_delete=django.db.models.deletion.CASCADE, related_name='product_apl', to='product.product')),
            ],
            options={
                'db_table': 'affiliated_product_links',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Category title', max_length=250, unique=True)),
                ('slug', models.SlugField(db_comment='Slug', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Creation datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Updated datetime')),
                ('user', models.ForeignKey(db_comment='User who created record', on_delete=django.db.models.deletion.CASCADE, related_name='user_pc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ProductCategories',
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_comment='Rating', default=1)),
                ('approved', models.BooleanField(db_comment='Approved', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Creation datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Updated datetime')),
                ('author', models.ForeignKey(db_comment='Feedback Author', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_comment='Product', on_delete=django.db.models.deletion.CASCADE, related_name='product_pf', to='product.product')),
            ],
            options={
                'db_table': 'product_feedbacks',
            },
        ),
    ]
