# Generated by Django 5.1.4 on 2024-12-12 00:05

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Blog title', max_length=255)),
                ('content', tinymce.models.HTMLField(db_comment='Blog post')),
                ('slug', models.SlugField(db_comment='Blog post slug', unique=True)),
                ('approved', models.BooleanField(db_comment='Blog Approval status', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Updated at')),
                ('author', models.ForeignKey(db_comment='Author', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_posts',
                'db_table_comment': 'Blogs Posts',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_comment='Comment')),
                ('approved', models.BooleanField(db_comment='Blog Approval status', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Updated at')),
                ('author', models.ForeignKey(db_comment='Comment author', on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to=settings.AUTH_USER_MODEL)),
                ('blog_post', models.ForeignKey(db_comment='Blog Post', on_delete=django.db.models.deletion.CASCADE, related_name='Blog_comments', to='blog.blogpost')),
            ],
            options={
                'db_table': 'blog_comments',
                'db_table_comment': 'Blogs Post Comments',
            },
        ),
    ]
